### ISSUE TITLE
KeyError: 'howcode.com.'

### ISSUE THREAD

**Issue by 1cedsoda** [howCodeORG/howDNS#1]
I cloned the repo and executed the dns.py.
After executing `dig howcode.org @127.0.0.1`  I got this error:
```
Traceback (most recent call last):
  File "dns.py", line 171, in <module>
    r = buildresponse(data)
  File "dns.py", line 145, in buildresponse
    ANCOUNT = len(getrecs(data[12:])[0]).to_bytes(2, byteorder='big')
  File "dns.py", line 94, in getrecs
    zone = getzone(domain)
  File "dns.py", line 86, in getzone
    return zonedata[zone_name]
KeyError: 'howcode.com.'
```

**Comment by tomus85** [comment]
I'm getting the same error, how do I fix this?

**Comment by root-Akshay** [comment]
Where did you store your zone file?
